# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore UnitTestProject

    - name: Build
      run: dotnet build UnitTestProject --no-restore
    - name: Test
      run: dotnet test ./UnitTestProject.Test/UnitTestProject.Test.csproj --filter "Category!=Integration"  --verbosity normal --logger "trx;LogFileName=xtest.trx" --results-directory "TestResults"
 
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:       
        trx_files: /home/runner/work/UnitTestProject/UnitTestProject/TestResults/xtest.trx   
